feat: ✨ catness and her friends are able to vote
cat-acronym-team/cat-me-if-you-can pull request #111
Opened 2022-11-06 23:27 UTC by gchamb

2022-11-07 20:55 UTC, nstringham requested changes, later dismissed

2022-11-07 20:55 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +  winner?: Role;
cam we have blank lines between properies please

2022-11-07 20:55 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +  votedOff?: string;
there should be a note here about the `NONE` specail value

maybe even set the type to `string | "NONE"`

2022-11-07 20:55 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +  VOTE: 30, //TODO: replace with correct timer when getting merged
don't forget this

2022-11-07 20:55 UTC, nstringham commented on client/src/lib/firebase/vote.ts
> +  setDoc(doc(getVoteCollection(lobbyCode), userId), {
should await or return so that erros can be caught and displayed to the uesr

2022-11-07 20:55 UTC, nstringham commented on functions/src/lobby.ts
> +    lobbyDocRef.set({ expiration }, { merge: true });
should probobly use update instead of set with merge: true

2022-11-07 20:55 UTC, nstringham commented on functions/src/vote.ts
> +    return b.votes - a.votes;
you could just do
```ts
return b.votes ?? 0 - a.votes ?? 0;
```

2022-11-07 20:55 UTC, nstringham commented on functions/src/vote.ts
> +        player.votes == most.votes
technically only need to check votes because it is unique

2022-11-07 20:55 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +  votedOff?: string;
this should be a uid

2022-11-07 20:55 UTC, nstringham commented on functions/src/vote.ts
> +    votedOff = most.displayName;
this should be a uid

2022-11-07 20:55 UTC, nstringham commented on functions/src/vote.ts
> +    }
why not just do `players[mostIndex].alive = false`

2022-11-07 20:55 UTC, nstringham commented on functions/src/vote.ts
> +    votedOff: votedOff == false ? "NONE" : votedOff,
if you initalized `votedOff`to `undifnined` then you can just do `votedOff ?? "NONE"`

2022-11-07 20:55 UTC, nstringham commented on functions/src/vote.ts
> +  transaction.update(lobbyDocRef, {
should return or await this

2022-11-07 20:55 UTC, nstringham commented on functions/src/lobby.ts
> +      findVoteOff(lobby, lobbyDocRef, transaction);
should await this

2022-11-07 20:55 UTC, nstringham commented on functions/src/lobby.ts
> +    return {};
what is the `{}` for?

2022-11-07 20:55 UTC, nstringham commented on functions/src/lobby.ts
> +    }
would it be better to make `vote` not optional and just set it to `0` from the very beginging?

2022-11-07 20:55 UTC, nstringham commented on client/src/components/Vote.svelte
> +          <img src="/avatars/{avatar}.webp" alt="cat picture {avatar}" />
please use the avatar alt text from `avatar.ts`

2022-11-07 20:55 UTC, nstringham commented on client/src/components/Vote.svelte
> +        <button class="avatar" on:click={() => addVote(lobbyCode, $user?.uid ?? "", lobby.uids[i])}>
should be disabled if it is the currently logged in player

2022-11-07 21:46 UTC, gchamb commented on functions/src/lobby.ts
> +      findVoteOff(lobby, lobbyDocRef, transaction);
it returns void tho not Promise<void>

2022-11-07 21:47 UTC, gchamb commented on functions/src/lobby.ts
> +    }
it would be better imo

2022-11-08 15:18 UTC, nstringham requested changes

2022-11-08 15:18 UTC, nstringham commented on functions/src/lobby.ts
> +      firestore.Timestamp.now().toMillis() + GAME_STATE_DURATIONS.END * 1000 // TODO: replace with correct timer when doing pull request
don't forget this

2022-11-08 15:18 UTC, nstringham commented on functions/src/vote.ts
> +  await transaction.update(lobbyDocRef, {
don't need this await

2022-11-08 15:18 UTC, nstringham commented on functions/src/lobby.ts
>  export const verifyExpiration = functions.https.onCall(async (data, context) => {
this should also have a return type

2022-11-08 15:53 UTC, nstringham approved these changes

2022-11-08 15:53 UTC, merged