feat: ✨ Delete Lobbies with Cron
cat-acronym-team/cat-me-if-you-can pull request #140
Opened 2022-11-15 14:29 UTC by gchamb

How to Test:

- Create a Lobby
- Change the expiration in the lobby doc to 24 hours ago or more
- Click the delete button on the splash screen page (Only there for testing)

2022-11-15 14:35 UTC, Muaad2001 approved these changes, later dismissed
checks out

2022-11-15 15:34 UTC, nstringham requested changes, later dismissed
looks pretty good don't forget to remove the testing things

2022-11-15 15:34 UTC, nstringham commented on functions/src/lobby.ts
> +    expiration: firestore.Timestamp.now(),
maybe set this to like 2 or 3 hours instead of instant

2022-11-15 15:34 UTC, nstringham commented on functions/src/lobby.ts
> +    expiration: firestore.Timestamp.now(),
don't forget to also do this when the game ends and the lobby goes back to WAIT

2022-11-15 15:34 UTC, nstringham commented on functions/src/cron.ts
> +  const dayFromTodaySecs = firestore.Timestamp.now().seconds - 86_400; // A day ago from today in seconds
I would prefer if this was `24 * 60 * 60`

2022-11-15 15:34 UTC, nstringham commented on functions/src/cron.ts
> +  const dayFromTodayDate = firestore.Timestamp.fromDate(new Date(dayFromTodaySecs * 1000)); // a day ago from today in date object
let's call these constants something that if obvious to everone that it refers to the past. maybe we could call it `oneDayAgo` or `twentyFourHoursAgo`

2022-11-17 14:55 UTC, mrjoshua520 approved these changes

2022-11-21 22:38 UTC, nstringham approved these changes

2022-11-21 22:38 UTC, merged