refactor(client) ♻️ put timer in game page
cat-acronym-team/cat-me-if-you-can pull request #143
Opened 2022-11-17 06:04 UTC by gchamb

- puts the timer in one spot on the game page
- removes timers from other components
- changed chatroom style since removing the p tag messed it up

2022-11-17 15:26 UTC, mrjoshua520 submitted a review, later dismissed

2022-11-19 15:06 UTC, nstringham requested changes, later dismissed
please pull from dev

2022-11-19 15:19 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +};
This file is for things in the database and DISPLAY_TIMERS seams to only be relivant to the client

2022-11-19 15:42 UTC, nstringham requested changes, later dismissed

2022-11-19 15:42 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +  WAIT: null,
what is the diffrence between null and false

2022-11-19 15:42 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +};
This file is for things in the database and DISPLAY_TIMERS seams to only be relivant to the client

2022-11-19 15:42 UTC, nstringham commented on client/src/routes/game/+page.svelte
> +      if (lobby?.state != newLobby?.state && newLobby?.state != null) {
`newLobby?.state != null`

is state ever null?

2022-11-19 15:42 UTC, nstringham commented on client/src/routes/game/+page.svelte
> +        countdown = GAME_STATE_DURATIONS[newLobby?.state];
why this `?`

2022-11-19 15:42 UTC, nstringham commented on client/src/routes/game/+page.svelte
> +  let timer: ReturnType<typeof setInterval>;
timer is never cleared

2022-11-19 15:42 UTC, nstringham commented on client/src/routes/game/+page.svelte
> +        }, 500);
probobly shouldn't be in onSnapshot

2022-11-19 15:42 UTC, nstringham commented on client/src/routes/game/+page.svelte
>    main {
can we have a blank line please

2022-11-19 15:42 UTC, nstringham commented on client/src/components/ChatRoom.svelte
>    }
this looks very bad on iPhone SE

2022-11-19 15:45 UTC, nstringham commented on client/src/components/Vote.svelte
> -  <p class="mdc-typography--headline4">Vote out the catfish</p>
you sure you wanna do that?

2022-11-22 15:16 UTC, nstringham approved these changes, later dismissed
the CSS is a little jank but we will fix it later

2022-11-22 15:34 UTC, nstringham approved these changes

2022-11-22 15:34 UTC, merged