feat(client) ✨: Add min/max players check
cat-acronym-team/cat-me-if-you-can pull request #146
Opened 2022-11-17 15:02 UTC by SBAsai

This PR will check if the minimum player count is met in order to start the current game session. It will also check if the maximum player count is met (lobby is full) and prevent more players from joining in. Each check will display an error accordingly.

2022-11-17 15:35 UTC, mrjoshua520 submitted a review, later dismissed

2022-11-18 17:27 UTC, mrjoshua520 submitted a review, later dismissed

2022-11-19 16:07 UTC, nstringham requested changes, later dismissed

2022-11-19 16:07 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +  minPlayers: number;
why are these not constants? I don't think these are configurable

2022-11-19 16:07 UTC, nstringham commented on functions/src/lobby.ts
> +      throw new functions.https.HttpsError("permission-denied", "Not enough players to start the game!");
this should probobly be `failed-precondition`

2022-11-19 16:07 UTC, nstringham commented on functions/src/lobby.ts
> +      throw new functions.https.HttpsError("permission-denied", "Lobby is full!");
this should probobly be `failed-precondition`

2022-11-19 16:07 UTC, nstringham commented on client/src/components/Lobby.svelte
> +  import { missing_component } from "svelte/internal";
I don't think you want to do this

2022-11-19 17:08 UTC, SBAsai commented on functions/src/firestore-types/lobby.ts
> +  minPlayers: number;
You mean like hard-coded values? I figured we may want to change the numbers depending on the number of catfish

2022-11-19 17:10 UTC, SBAsai commented on client/src/components/Lobby.svelte
> +  import { missing_component } from "svelte/internal";
It's not being used so I think VSCode just auto imported it when I was doing something

2022-11-21 22:19 UTC, SBAsai commented on functions/src/firestore-types/lobby.ts
> +  minPlayers: number;
I updated this comment section to describe the reason it needs to be configurable for now.

2022-11-22 16:51 UTC, nstringham requested changes, later dismissed
the start game button should be disabled if the game cannot be started

2022-11-22 16:51 UTC, nstringham commented on client/src/components/Lobby.svelte
> +        <h3 class="error">{minPlayers - lobby.players.length} more player required to start game...</h3>
this could be `1` instead of `{minPlayers - lobby.players.length}`

2022-11-22 16:51 UTC, nstringham commented on client/src/components/Lobby.svelte
> +  let minPlayers = lobby.catfishAmount * 2 + 2;
this should be reactive incase the host changes the game setting

2022-11-28 19:23 UTC, gchamb commented
`on line 2 ` in Lobby.svelte you have an unused component

2022-11-28 19:28 UTC, gchamb commented on client/src/components/Lobby.svelte
>    {#if auth.currentUser?.uid === lobby.uids[0]}
This probably wasn't you but we should be using the authstore here

2022-11-28 19:29 UTC, gchamb commented on client/src/components/Lobby.svelte
>    {#if auth.currentUser?.uid === lobby.uids[0]}
`on line 11` use the authstore. I know that probably wasn't you who added it

2022-11-28 19:31 UTC, gchamb submitted a review, later dismissed
see above

2022-11-29 14:34 UTC, gchamb approved these changes

2022-11-29 15:23 UTC, mrjoshua520 approved these changes

2022-11-29 15:37 UTC, merged