feat(client): ✨ Show users answer on prompt page when they click done
cat-acronym-team/cat-me-if-you-can pull request #157
Opened 2022-11-22 15:37 UTC by Muaad2001

2022-11-22 17:22 UTC, nstringham commented on client/src/components/Prompt.svelte
> +    <Button type="submit" disabled={error != undefined} on:click={showAnswer}><Label>Done</Label></Button>
this should be in the submit event listner on the form

2022-11-22 17:24 UTC, nstringham commented on client/src/components/Prompt.svelte
> +    {#if showUserAnswer}
why not just do `displayAnswer != ""` or even make displayAnswer start as undefined and display if it is not undefined

2022-11-22 17:26 UTC, nstringham requested changes
I think this would be better if it was doing database reads like we do for voting but I guess it's ok like this

2022-11-29 15:34 UTC, zaverbac approved these changes

2022-12-01 14:56 UTC, SBAsai commented
I think that when the timer hits 0:00, you shouldn't be able to keep entering in answers and have `Your Answer:` pop up when the answer isn't saved

2022-12-01 16:46 UTC, nstringham commented
> I think that when the timer hits 0:00, you shouldn't be able to keep entering in answers and have `Your Answer:` pop up when the answer isn't saved

I like this idea but it should probably be another card

I created #166 which would resolve this

2022-12-01 16:57 UTC, nstringham approved these changes

2022-12-01 16:58 UTC, nstringham commented
Requesting @gchamb's review because I think he said he wanted this to be a database subscription

2022-12-01 18:50 UTC, nstringham commented
merging this and moving the firebase reads to #167

2022-12-01 18:51 UTC, merged