feat(client): ✨ Add lobby settings
cat-acronym-team/cat-me-if-you-can pull request #165
Opened 2022-12-01 03:53 UTC by mrjoshua520

2022-12-01 15:48 UTC, SBAsai submitted a review, later dismissed
Nate mentioned changing the labels to be on one line instead of two as a reminder

2022-12-01 15:48 UTC, SBAsai commented on client/src/components/LobbySettings.svelte
> +            step={1}
Steps for `catfishValue` don't show up for me

2022-12-01 15:48 UTC, SBAsai commented on client/src/components/LobbySettings.svelte
> +            step={1}
I think since the steps are floating above the slider, the step goes outside of the container so it's probably just a margin issue

2022-12-01 15:48 UTC, SBAsai commented on client/src/components/LobbySettings.svelte
> +          <Slider
It might be more user-friendly to have minutes:seconds instead of something like 280 seconds since that is harder to gauge immediately

2022-12-01 15:48 UTC, SBAsai commented on client/src/components/LobbySettings.svelte
> +          <Slider
If we do use seconds tho these should probably have "seconds" after the number

2022-12-01 15:48 UTC, SBAsai commented on client/src/components/LobbySettings.svelte
> +        <Button on:click={() => apply(catfishValue, promptTimerValue, chatTimerValue, voteTimerValue)} action="close"
This don't close

2022-12-01 16:07 UTC, SBAsai commented on functions/src/lobby.ts
> +      throw new functions.https.HttpsError("permission-denied", "Cannot have less than 1 or more than 3 catfish!");
I think this is supposed to be `if (data.catfishNumber < 1 || data.catfishNumber > 3)` instead of `data.chatTimer`

2022-12-01 22:36 UTC, nstringham submitted a review, later dismissed
the sliders are not aligned
![image](https://user-images.githubusercontent.com/44071655/205173488-61c73345-be7b-4d2b-af77-84313a5236a8.png)

2022-12-01 22:36 UTC, nstringham commented on client/src/components/Lobby.svelte
> +    <div class="lobby-info-level">
lets give this class a better name

2022-12-01 22:36 UTC, nstringham commented on client/src/routes/game/+page.svelte
> +        countdown = GAME_STATE_DURATIONS_DEFAULT[newLobby.state];
are you sure this should be DEFAULT?

2022-12-01 22:36 UTC, nstringham commented on functions/src/vote.ts
> +    firestore.Timestamp.now().toMillis() + GAME_STATE_DURATIONS_DEFAULT.RESULT * 1000
are you sure this should be DEFAULT?

2022-12-01 22:36 UTC, nstringham commented on functions/src/role.ts
> +    firestore.Timestamp.now().toMillis() + GAME_STATE_DURATIONS_DEFAULT.ROLE * 1000
are you sure this should be DEFAULT?

2022-12-01 22:36 UTC, nstringham commented on functions/src/firebase-functions-types.ts
> +}
you should make tests for this function.
look at `functions/tests/functions-types/avatar.test.ts` for an example

2022-12-01 22:36 UTC, nstringham commented on functions/src/firebase-functions-types.ts
> +}
there are some security issues that I think will become clear to you when you make the tests

2022-12-01 22:36 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +  voteTime: number;
these comments should say what the unit is (seconds? minutes? ms? ns?)

2022-12-01 22:36 UTC, nstringham commented on functions/src/firestore-types/lobby.ts
> +  catfishAmount: number;
this comment makes it sound like if a catfist dies then this number will go down

2022-12-01 22:36 UTC, nstringham commented on functions/src/lobby.ts
> +    }
these could be before the transaction so that if it fails then we don't need to do a database write if we get invalid data

2022-12-01 22:36 UTC, nstringham commented on functions/src/lobby.ts
> +  }
you should consider destructing `data.lobbySettings` to make code less verbose
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +  ]);
this should proboly just be a object of type `{ [state in ConfigurableTimer]: string }`

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +  ]);
these are unessisary because you could just use `GAME_STATE_DURATIONS_MIN` and `GAME_STATE_DURATIONS_MAX` directly

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +  }
why not just import `formatTimer` from `time.ts`

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +  async function apply(catfish: number, prompt: number, chat: number, vote: number) {
why not just use the variables instead of having function args?

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +    fullscreen
have we tried this as a non-fullscreen dialog

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +    aria-describedby="rules-dialog-content"
these need to refer to the ids of elements

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +            input$aria-label="Discrete slider"
this needs to refer to the id of an element

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +            style={"width:80%;"}
percent is rarly a good idea

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +    }}
if you do `on:click={() => (showLobbySettings = true)}` then you can put it on one line

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +    return ": " + minutes + ":" + seconds;
this shows `2:5` when it should show `2:05`

2022-12-01 22:36 UTC, nstringham commented on client/src/components/LobbySettings.svelte
> +      <Button on:click={() => apply(catfishValue, promptTimerValue, chatTimerValue, voteTimerValue)} action="close"
doesn't it still close the dialog if you don't say `action="close"`

2022-12-01 22:37 UTC, nstringham commented on functions/src/vote.ts
> +    firestore.Timestamp.now().toMillis() + GAME_STATE_DURATIONS_DEFAULT.RESULT * 1000
oh wait yeah duh

2022-12-01 22:37 UTC, nstringham commented on functions/src/role.ts
> +    firestore.Timestamp.now().toMillis() + GAME_STATE_DURATIONS_DEFAULT.ROLE * 1000
oh wait yeah duh

2022-12-05 20:25 UTC, gchamb commented on functions/src/firestore-types/lobby.ts
> +   * the number players that will be catfish
add of after number

2022-12-05 20:32 UTC, gchamb commented on functions/src/chat.ts
>    transaction.update(lobbyDoc, { state: "VOTE", players });
remove this line muadd didn't do correct merge conflicts

2022-12-05 20:38 UTC, gchamb commented on functions/src/lobby.ts
> +        voteTime: data.lobbySettings.voteTime,
you created a variable up top called settings so you didnt have to do this long typing

2022-12-05 20:54 UTC, gchamb commented
pull from dev

2022-12-05 20:56 UTC, gchamb commented on client/src/components/LobbySettings.svelte
> +      errorMessage = err instanceof Error ? err.message : String(err);
do you display this anywhere

2022-12-05 21:00 UTC, gchamb commented on client/package.json
> +    "@smui/form-field": "^7.0.0-beta.0",
is this being used anywhere

2022-12-05 21:01 UTC, gchamb requested changes, later dismissed
see above

2022-12-05 21:12 UTC, mrjoshua520 commented on client/package.json
> +    "@smui/form-field": "^7.0.0-beta.0",
It probably isn't while me and Nate were doing CSS stuff he had said to not fully remove until we make sure though

2022-12-05 21:27 UTC, mrjoshua520 commented on client/package.json
> +    "@smui/form-field": "^7.0.0-beta.0",
@nstringham

2022-12-06 08:09 UTC, nstringham approved these changes

2022-12-06 08:10 UTC, merged