fix(functions): 🐛 stalker prompt shows and no multiple stalkers
cat-acronym-team/cat-me-if-you-can pull request #189
Opened 2022-12-08 01:24 UTC by gchamb

This shows the stalker's prompt answer and fixes the multiple stalker/spectator problem.

ignore the branch name should just be gchamb/fix-stalker

2022-12-08 01:58 UTC, mrjoshua520 submitted a review, later dismissed
Looks great! Someone else should look at it before merging though

2022-12-08 16:41 UTC, nstringham submitted a review, later dismissed
we decided we should not delete prompt answers at the end pf prompt and use that at the beginning of vote and we should also delete chat messages asyncrounstly after setting the state t vote

2022-12-10 18:27 UTC, nstringham requested changes, later dismissed
one disavantage of what we are doing here iswe read the prompt awnsers twice at the end of chat once in `setAnswers` and once in `deletePromptAnswers` we could store if and reuse it but I think this is probobly fine for now

2022-12-10 18:27 UTC, nstringham commented on functions/src/lobby.ts
> +    await deletePromptAnswers(lobbyDocRef);
why are prompt answers being deleted twice?

2022-12-10 18:27 UTC, nstringham commented on functions/src/chat.ts
> +    chatMessages.docs.map((messageDoc) => batch.delete(messageDoc.ref));
this does not return anything so it should be a map.

maybe conside a for of loop

2022-12-10 18:27 UTC, nstringham commented on functions/src/chat.ts
> +    if (promptAns === "" || !promptAnswerDoc.exists) {
don't need to check `!promptAnswerDoc.exists` because querries already garentee that the documents exist

2022-12-10 18:27 UTC, nstringham commented on functions/src/chat.ts
> +    players[playerIndex].promptAnswer = promptAns;
I feel like this could just be `players[playerIndex].promptAnswer = promptData.answer ?? "no answer"`

2022-12-11 17:57 UTC, nstringham approved these changes

2022-12-11 18:04 UTC, mrjoshua520 approved these changes

2022-12-11 18:04 UTC, merged