Signin feature
cat-acronym-team/cat-me-if-you-can pull request #48
Opened 2022-09-30 02:07 UTC by zaverbac

2022-09-30 21:17 UTC, nstringham requested changes
Can you please remove all the unused images

2022-09-30 21:19 UTC, nstringham requested changes
Please read over the linting errors and understand what they are saying and fix them if appropriate

2022-09-30 21:21 UTC, nstringham commented
it might be a good idea to make a file for auth instead of putting it all in the firebase file

2022-10-01 18:43 UTC, zaverbac commented
Completed all suggestions in review

2022-10-02 17:18 UTC, nstringham requested changes

2022-10-02 17:18 UTC, nstringham commented on client/src/lib/firebase/authfunctions.ts
> +  });
it looks like we are not using any of these values so we probobly don't need the then block

2022-10-02 17:18 UTC, nstringham commented on client/src/lib/firebase/authfunctions.ts
> +  signInWithPopup(auth, provider).then((result) => {
`signInWithPopup` is asyncronous so it should be awaited or returned

2022-10-02 17:18 UTC, nstringham commented on client/src/lib/firebase/authfunctions.ts
> +  signInWithPopup(auth, provider);
`signInWithPopup` is asyncronous so it should be awaited or returned

2022-10-02 17:18 UTC, nstringham commented on client/src/lib/firebase/authfunctions.ts
> +  signInAnonymously(auth);
`signInAnonymously` is asyncronous so it should be awaited or returned

2022-10-04 14:15 UTC, nstringham commented
related to #27

2022-10-04 17:50 UTC, nstringham requested changes
Once you remove `authstore.ts` it should be good enough to merge and then we can make it better later

2022-10-04 17:50 UTC, nstringham commented on client/src/lib/stores/authstore.ts
> +}
I think we should remove this in favor of rxfire

2022-10-04 17:51 UTC, nstringham commented on client/src/routes/signin/+page.svelte
> +      ". . . . . . . . .";
If you are trying to center you should consider using `place-content`
https://css-tricks.com/snippets/css/complete-guide-grid/#aa-place-content

2022-10-05 20:20 UTC, nstringham approved these changes
Good enough for now

2022-10-05 20:33 UTC, merged