feat(client): ✨ Add CreateLobby to Dev
cat-acronym-team/cat-me-if-you-can pull request #56
Opened 2022-10-06 14:34 UTC by mrjoshua520

2022-10-06 15:53 UTC, nstringham requested changes, later dismissed

2022-10-06 15:53 UTC, nstringham commented on client/src/lib/firebase/create-lobby.ts
> +  const checkCode = await getDocs(lobbyCollection);
let's not download the entire lobbies collection :)

2022-10-08 18:59 UTC, gchamb approved these changes

2022-10-08 19:00 UTC, merged

2022-10-10 19:53 UTC, nstringham commented on client/src/routes/+page.svelte
> +    const code = (await createLobby()) as string;
lets not have the `as` here because is isn't needed

2022-10-10 19:53 UTC, nstringham commented on client/src/routes/+page.svelte
> +    const code = (await createLobby()) as string;
@mrjoshua520